spring.application.name=spring-api-rest
server.port=3000
spring.datasource.url=mysql://localhost:3306/
spring.datasource.username=root
spring.datasource.password=root
spring.profiles.active=${ACTIVE_PROFILE:dev}